---
sidebar: sidebar 
permalink: concept-data-services.html 
keywords: data services, data protection, data mobility, backup, replication, netapp console 
summary: Informationen zur Verwendung von NetApp Backup and Recovery in der lokalen NetApp Console-Bereitstellung zum Schutz und zur Verwaltung Ihrer Daten. 
---
= Informationen zu NetApp Backup and Recovery in der lokalen Bereitstellung der NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery ist ein Datendienst, der effizienten, sicheren und kostengünstigen Datenschutz für alle Ihre ONTAP Workloads bietet, einschließlich Volumes, Datenbanken, virtuellen Maschinen und Kubernetes Workloads.

Eine Workload ist eine logische Gruppierung von Ressourcen innerhalb eines Systems, die als Einheit für Schutz, Verwaltung, Erkennung und Wiederherstellung verwaltet wird. Im Bereich Backup und Recovery ist eine Workload die zu schützende Einheit. Ihre Bedeutung hängt von der Datenquelle ab: In Kubernetes ist eine Workload eine Anwendung, in VM-Umgebungen eine virtuelle Maschine und in Datenbankumgebungen eine Datenbank.

Die Unterstützung für Backup und Recovery ist in allen ONTAP-Systemen bereits integriert, sodass keine zusätzliche Hardware oder Mediengateways benötigt werden. Dies macht Backup-Operationen einfach und kosteneffektiv. Die NetApp Console vereinfacht die Implementierung jeder Backup-Strategie, einschließlich des gesamten Spektrums der 3-2-1-Backup-Varianten, ohne dass mehrere Ressourcenmanager oder spezialisiertes Personal erforderlich sind.


NOTE: NetApp Backup and Recovery befindet sich für die NetApp Console lokale Bereitstellung im Vorschaumodus. Der Dienst ist noch nicht allgemein verfügbar, und die Funktionen und die Funktionalität können sich ändern.

link:https://docs.netapp.com/us-en/data-services-backup-recovery/index.html["Weitere Informationen zu NetApp Backup and Recovery."^].
