---
sidebar: sidebar 
permalink: reference-ports-on-prem.html 
keywords: networking, network requirements, ports, on-premises, TCP, UDP, firewall, connectivity requirements, Console agent, agent connectivity, netapp console local, inbound ports, OVA 
summary: Die NetApp Console lokale OVA-Bereitstellung verwaltet ihre eigene interne Firewall. Wenn in Ihrer Umgebung eine externe Firewall-Richtlinie für die VM gilt, müssen die folgenden eingehenden Ports von Ihren Management-Hosts aus erreichbar sein. 
---
= Eingehende Ports für die lokale NetApp Console-Bereitstellung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die NetApp Console lokale OVA-Bereitstellung verwaltet ihre eigene interne Firewall. Wenn in Ihrer Umgebung eine externe Firewall-Richtlinie für die VM gilt, müssen die folgenden eingehenden Ports von Ihren Management-Hosts aus erreichbar sein.

[cols="10,10,80"]
|===
| Port | Protokoll | Zweck 


| 22 | TCP | SSH für Fernwartung und Zugriff auf die Diagnoseshell 


| 123 | UDP | NTP zur Zeitsynchronisation 


| 2379 | TCP | etcd Client API für RKE2 Control-Plane etcd Client Traffic 


| 2380 | TCP | etcd Peer Port für die etcd Mitglied-zu-Mitglied-Replikation 


| 6443 | TCP | Kubernetes API Server für kubectl- und RKE2-API-Zugriff 


| 8472 | UDP | Canal/Flannel VXLAN Overlay für Pod-zu-Pod-Datenverkehr zwischen RKE2-Knoten 


| 9091 | TCP | Calico Felix Metriken-Endpunkt für CNI-Gesundheit und Metriken 


| 9100 | TCP | Prometheus node_exporter für das Scraping von Host-Metriken 


| 9345 | TCP | RKE2 Supervisor und Server-Registrierungsendpunkt 


| 10250 | TCP | Kubelet API für metrics-server und kube-apiserver zu kubelet 
|===