---
sidebar: sidebar 
permalink: reference-local-known-limitations.html 
keywords: console local deployment, known limitations, unsupported platforms, unsupported devices, unsupported functions, IP range 
summary: Referenz für bekannte Einschränkungen bei der lokalen Bereitstellung der NetApp Console. 
---
= Bekannte Einschränkungen bei der lokalen Bereitstellung der NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bekannte Einschränkungen kennzeichnen Plattformen, Geräte oder Funktionen, die von dieser Produktversion nicht unterstützt werden oder nicht korrekt mit ihr zusammenarbeiten. Überprüfen Sie diese Einschränkungen sorgfältig.

Diese Einschränkungen gelten speziell für die Einrichtung der NetApp Console und die Administration: den Agenten, die Software-as-a-Service (SaaS) Plattform und mehr.



[[console-vm-limitations]]
== Einschränkungen der Console-VM



[[possible-conflict-with-ip-addresses-in-the-10-42-0-016-and-10-43-0-016-ranges]]
=== Möglicher Konflikt mit IP-Adressen in den Bereichen 10.42.0.0/16 und 10.43.0.0/16

NetApp Console lokale Bereitstellung verwendet einen festen Adressraum für die Kommunikation zwischen den Diensten. Die IP-Bereiche 10.42.0.0/16 und 10.43.0.0/16 werden für das interne Netzwerk verwendet. Vor der Bereitstellung der Console lokalen Bereitstellung ist sicherzustellen, dass diese IP-Bereiche nicht anderen VM-Instanzen, DHCP-Bereichen, DNS-Einträgen oder Load Balancer VIP-Pools in den für die Console lokale Bereitstellung verfügbaren VLANs zugewiesen sind.

Im Knowledge Base Artikel „Agent IP conflict with existing network“ finden sich Anweisungen zum Ändern der IP-Adresse der Schnittstellen des Agenten.



[[shared-linux-hosts-are-not-supported]]
=== Shared Linux Hosts werden nicht unterstützt

Der Agent wird auf einer VM, die auch von anderen Anwendungen genutzt wird, nicht unterstützt. Die VM muss ausschließlich für die Agentensoftware reserviert sein.



[[third-party-agents-and-extensions]]
=== Drittanbieter-Agenten und Erweiterungen

Agenten von Drittanbietern oder VM-Erweiterungen werden auf der Agent-VM nicht unterstützt.
