---
sidebar: sidebar 
permalink: task-get-help.html 
keywords: help, ticket, open support case, support, netapp support, technical support, call support, open ticket, web ticket, open an issue 
summary: 'NetApp bietet Unterstützung für die lokale Bereitstellung der NetApp Console auf vielfältige Weise. Umfangreiche kostenlose Selbsthilfeoptionen stehen 24x7 zur Verfügung, wie zum Beispiel Knowledge Base (KB)-Artikel und ein Community-Forum. Die Support-Registrierung umfasst technischen Remote-Support über Web-Ticketing.' 
---
= Hilfe zur lokalen Bereitstellung der NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp bietet Unterstützung für die lokale Bereitstellung von NetApp Console auf vielfältige Weise. Umfangreiche kostenlose Selbsthilfeoptionen stehen 24x7 zur Verfügung, wie zum Beispiel Knowledge Base (KB)-Artikel und ein Community-Forum. Eine Registrierung für den Support ist mit der Seriennummer einer beliebigen Speicherressource möglich, die mit der lokalen Bereitstellung von NetApp Console verknüpft ist. Die Registrierung umfasst technischen Remote-Support über Web-Ticketing.



[[use-self-support-options]]
== Selbsthilfeoptionen verwenden

Diese Optionen stehen Ihnen kostenlos 24 Stunden am Tag, 7 Tage die Woche zur Verfügung:

* Dokumentation
+
Die NetApp Console Dokumentation zur lokalen Bereitstellung, die Sie gerade ansehen.

* https://kb.netapp.com/Cloud/BlueXP["Wissensdatenbank"^]
+
In der NetApp Knowledge Base nach Artikeln suchen, die bei der Fehlerbehebung unterstützen.





[[open-a-support-case-with-netapp-console-local-deployment]]
== Einen Supportfall mit der NetApp Console lokalen Bereitstellung eröffnen

Ein Supportfall kann mit einer der NetApp Seriennummern des Speichersystems eröffnet werden, die über Ihre NetApp Console lokale Bereitstellungsumgebung verwaltet werden.

.Schritte
. Wechseln Sie zu  https://mysupport.netapp.com["NetApp Support Site"^] und melden Sie sich mit Ihren NetApp Support-Zugangsdaten an.
. *Fälle und Teile > Technischen Fall erstellen* auswählen.
. Geben Sie die Seriennummer des NetApp Speichersystems ein, das mit dem Console lokalen Bereitstellungsprodukt verknüpft ist, bei dem das Problem auftritt.
. Erstellen Sie einen neuen Fall und wählen Sie den passenden Kategoriecode für die lokale NetApp Console-Bereitstellung aus.




[[download-a-support-bundle]]
== Ein Support-Paket herunterladen

Ein Supportpaket enthält aktuelle Protokolle und Konfigurationsinformationen. Das neueste Paket kann heruntergeladen und bei Bedarf an den technischen Support von NetApp gesendet werden.

.Schritte
. *Administration > Support* auswählen, um die Support-Seite anzuzeigen.
. Auf der Support-Karte *Erstellen* auswählen, um ein Paket aus Protokollen und Konfigurationsdaten zu erstellen.
. Sobald das Paket erstellt ist, *Herunterladen* auswählen. Es erscheint eine Aufforderung, eine ZIP-Datei herunterzuladen.
+
Das System verwaltet jeweils nur ein Support Bundle. Das Erstellen eines neuen Support Bundles ersetzt das vorherige.


