= 
:allow-uri-read: 


Nachdem Sie den Console Agent installiert und eingerichtet haben, fügen Sie Ihre Cloud-Anmeldeinformationen hinzu, damit der Console Agent über die erforderlichen Berechtigungen verfügt, um Aktionen in AWS oder Azure durchzuführen.

[role="tabbed-block"]
====
.AWS
--
.Bevor Sie beginnen
Wenn Sie diese AWS-Anmeldeinformationen gerade erst erstellt haben, kann es einige Minuten dauern, bis sie verfügbar sind. Einige Minuten sollten vergehen, bevor die Anmeldeinformationen zur Konsole hinzugefügt werden.

.Schritte
. *Administration > Anmeldeinformationen* auswählen.
. *Organisationsanmeldeinformationen* auswählen.
. *Anmeldeinformationen hinzufügen* auswählen und den Schritten im Assistenten folgen.
+
.. *Speicherort der Anmeldeinformationen*: *Amazon Web Services > Agent* auswählen.
.. *Anmeldeinformationen definieren*: Es sind ein AWS-Zugriffsschlüssel und ein geheimer Schlüssel einzugeben.
.. *Marketplace Subscription*: Ein Marketplace-Abonnement kann mit diesen Zugangsdaten verknüpft werden, indem jetzt ein Abonnement abgeschlossen oder ein bestehendes Abonnement ausgewählt wird.
.. *Überprüfung*: Die Angaben zu den neuen Zugangsdaten bestätigen und *Hinzufügen* auswählen.




Sie können jetzt zur  https://console.netapp.com["NetApp Console"^]gehen, um den Console Agent zu verwenden.

--
.Azure
--
.Bevor Sie beginnen
Wenn Sie diese Azure-Anmeldeinformationen gerade erst erstellt haben, kann es einige Minuten dauern, bis sie verfügbar sind. Es sollten einige Minuten abgewartet werden, bevor die Anmeldeinformationen dem Console Agent hinzugefügt werden.

.Schritte
. *Administration > Anmeldeinformationen* auswählen.
. *Anmeldeinformationen hinzufügen* auswählen und den Schritten im Assistenten folgen.
+
.. *Speicherort der Anmeldeinformationen*: *Microsoft Azure > Agent* auswählen.
.. *Anmeldeinformationen definieren*: Geben Sie Informationen zum Microsoft Entra Service Principal ein, der die erforderlichen Berechtigungen gewährt:
+
*** Anwendungs-ID (Client)
*** Verzeichnis-ID (Mandanten-ID)
*** Client-Secret


.. *Marketplace Subscription*: Ein Marketplace-Abonnement kann mit diesen Zugangsdaten verknüpft werden, indem jetzt ein Abonnement abgeschlossen oder ein bestehendes Abonnement ausgewählt wird.
.. *Überprüfung*: Die Angaben zu den neuen Zugangsdaten bestätigen und *Hinzufügen* auswählen.




.Ergebnis
Der Konsolenagent verfügt nun über die erforderlichen Berechtigungen, um in Azure in Ihrem Namen Aktionen durchzuführen. Jetzt kann zur  https://console.netapp.com["NetApp Console"^] gewechselt werden, um den Konsolenagenten zu verwenden.

--
====