= 
:allow-uri-read: 


Eine Rolle wird erstellt und auf ein Dienstkonto angewendet, das für die Console-Agenten-VM-Instanz verwendet wird.

.Schritte
. Erstellen einer benutzerdefinierten Rolle in Google Cloud:
+
.. Erstellen Sie eine YAML-Datei, die die im link:reference-permissions-gcp.html["Console-Agentenrichtlinie für Google Cloud"] definierten Berechtigungen enthält.
.. In Google Cloud die Cloud Shell aktivieren.
.. Die YAML-Datei mit den erforderlichen Berechtigungen für den Console-Agenten hochladen.
.. Eine benutzerdefinierte Rolle kann mit dem  `gcloud iam roles create` Befehl erstellt werden.
+
Das folgende Beispiel erstellt eine Rolle mit dem Namen „connector“ auf Projektebene:

+
[source, gcloud]
----
gcloud iam roles create connector --project=myproject --file=connector.yaml
----
+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Google Cloud-Dokumentation: Erstellen und Verwalten benutzerdefinierter Rollen"^]



. Ein Dienstkonto in Google Cloud erstellen:
+
.. Im IAM & Admin-Dienst *Dienstkonten > Dienstkonto erstellen* auswählen.
.. Servicekontodetails eingeben und *Erstellen und Fortfahren* auswählen.
.. Wählen Sie die Rolle aus, die Sie gerade erstellt haben.
.. Führen Sie die verbleibenden Schritte zur Erstellung der Rolle aus.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Google Cloud-Dokumentation: Erstellen eines Dienstkontos"^]





.Ergebnis
Sie verfügen nun über ein Dienstkonto, das Sie der Console Agent VM-Instanz zuweisen können.
