= 
:allow-uri-read: 


.Bevor Sie beginnen
Folgendes sollte vorhanden sein:

* Root-Rechte zum Installieren des Console-Agenten.
* Details zu einem Proxyserver, falls ein Proxy für den Internetzugriff vom Console-Agent benötigt wird.
+
Es besteht die Möglichkeit, einen Proxyserver nach der Installation zu konfigurieren, was jedoch einen Neustart des Console-Agenten erfordert.

* Ein von einer Zertifizierungsstelle signiertes Zertifikat, wenn der Proxyserver HTTPS verwendet oder wenn der Proxy ein abfangender Proxy ist.



NOTE: Bei der manuellen Installation des Console-Agenten kann kein Zertifikat für einen transparenten Proxyserver festgelegt werden. Wenn ein Zertifikat für einen transparenten Proxyserver festgelegt werden muss, ist nach der Installation die Maintenance Console zu verwenden. Weitere Informationen zur link:reference-agent-maint-console.html["Agent-Wartungskonsole"].

.Über diese Aufgabe
Das auf der NetApp Support Site verfügbare Installationsprogramm ist möglicherweise eine frühere Version. Nach der Installation aktualisiert sich der Console Agent automatisch, wenn eine neue Version verfügbar ist.

.Schritte
. Falls die Systemvariablen _http_proxy_ oder _https_proxy_ auf dem Host gesetzt sind, müssen diese entfernt werden:
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
Wenn Sie diese Systemvariablen nicht entfernen, schlägt die Installation fehl.

. Die Console Agent-Software von der  https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["NetApp Support Site"^]Website herunterladen und anschließend auf den Linux-Host kopieren.
+
Es empfiehlt sich, den „Online“-Agenten-Installer herunterzuladen, der für die Verwendung in Ihrem Netzwerk oder in der Cloud vorgesehen ist.

. Berechtigungen zum Ausführen des Skripts zuweisen.
+
[source, cli]
----
chmod +x NetApp-Console-Agent-<version>
----
+
Dabei steht <version> für die Version des Console-Agenten, die Sie heruntergeladen haben.

. Das Installationsskript ausführen.
+
[source, cli]
----
 ./NetApp-Console-Agent-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
Sie müssen Proxy-Informationen hinzufügen, falls Ihr Netzwerk einen Proxy für den Internetzugang benötigt. Es kann entweder ein transparenter oder ein expliziter Proxy hinzugefügt werden. Die Parameter --proxy und --cacert sind optional und es erfolgt keine Aufforderung, diese anzugeben. Wenn ein Proxyserver vorhanden ist, müssen die Parameter wie gezeigt eingegeben werden.

+
Hier ist ein Beispiel für die Konfiguration eines expliziten Proxyservers mit einem CA-signierten Zertifikat:

+
[source, cli]
----
 ./NetApp-Console-Agent-v4.0.0--proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
--proxy konfiguriert den Console-Agenten zur Verwendung eines HTTP- oder HTTPS-Proxyservers in einem der folgenden Formate:

+
** http://address:port
** http://user-name:password@address:port
** \http://Domain-Name%92Benutzername:Passwort@Adresse:Port
** \https://adresse:port
** https://user-name:password@address:port
** https://domain-name%92user-name:password@address:port
+
Dabei ist Folgendes zu beachten:

+
*** Der Benutzer kann ein lokaler Benutzer oder ein Domänenbenutzer sein.
*** Für einen Domänenbenutzer muss der ASCII-Code für einen \ wie oben gezeigt verwendet werden.
*** Der Console-Agent unterstützt keine Benutzernamen oder Passwörter, die das @-Zeichen enthalten.
*** Enthält das Passwort eines der folgenden Sonderzeichen, muss dieses Sonderzeichen durch Voranstellen eines Backslashs maskiert werden: & oder !
+
Beispiel:

+
\http://bxpproxyuser:netapp1\!@address:3128

+
--cacert gibt ein von einer Zertifizierungsstelle signiertes Zertifikat an, das für den HTTPS-Zugriff zwischen dem Console Agent und dem Proxyserver verwendet wird. Dieser Parameter ist für HTTPS-Proxyserver, Intercepting-Proxyserver und transparente Proxyserver erforderlich.



+
Hier ist ein Beispiel für die Konfiguration eines transparenten Proxyservers. Bei der Konfiguration eines transparenten Proxyservers muss der Proxyserver nicht definiert werden. Es wird lediglich ein von einer Zertifizierungsstelle signiertes Zertifikat zum Console-Agent-Host hinzugefügt:



+
[source, cli]
----
 ./NetApp-Console-Agent-v4.0.0 --cacert /tmp/cacert/certificate.cer
----
. Wenn Sie Podman verwendet haben, müssen Sie den aardvark-dns Port anpassen.
+
.. SSH-Verbindung zur virtuellen Maschine des Console-Agenten herstellen.
.. Die Datei podman _/usr/share/containers/containers.conf_ öffnen und den gewählten Port für den Aardvark DNS-Service anpassen. Zum Beispiel auf 54 ändern.
+
[source, cli]
----
vi /usr/share/containers/containers.conf
...
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
...
Esc:wq
----
.. Die virtuelle Maschine des Console-Agenten neu starten.




. Warten Sie, bis die Installation abgeschlossen ist.
+
Am Ende der Installation wird der Konsolenagentendienst (occm) zweimal neu gestartet, wenn ein Proxyserver angegeben wurde.

. Einen Webbrowser auf einem Host mit Verbindung zur virtuellen Maschine des Console-Agenten öffnen und die folgende URL eingeben:
+
https://_ipaddress_[]

. Nach der Anmeldung wird der Konsolenagent eingerichtet:
+
.. Die Organisation angeben, die dem NetApp Console-Agenten zugeordnet werden soll.
.. Geben Sie einen Namen für das System ein.
.. Unter *Befinden Sie sich in einer sicheren Umgebung?* bleibt der eingeschränkte Modus deaktiviert.
+
Sie sollten den eingeschränkten Modus deaktiviert lassen, da diese Schritte die Verwendung der Konsole im Standardmodus beschreiben. Der eingeschränkte Modus sollte nur aktiviert werden, wenn eine sichere Umgebung vorliegt und dieses Konto von Backend-Services getrennt werden soll. Ist dies der Fall, link:task-quick-start-restricted-mode.html["Schritte zum Einstieg in die NetApp Console im eingeschränkten Modus"].

.. *Los geht's* auswählen.



